import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./fix.scss";
import "@gravity-ui/page-constructor/styles/styles.scss";
import "./globals.css";

const geistSans = Montserrat({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${geistSans.variable}`}>{children}</body>
    </html>
  );
}
